//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPlantilla.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dimacodevEntities : DbContext
    {
        public dimacodevEntities()
            : base("name=dimacodevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auxiliar> auxiliar { get; set; }
        public virtual DbSet<colaborador> colaborador { get; set; }
        public virtual DbSet<colaboradorHojaRuta> colaboradorHojaRuta { get; set; }
        public virtual DbSet<costosHojaRuta> costosHojaRuta { get; set; }
        public virtual DbSet<estadoEntrega> estadoEntrega { get; set; }
        public virtual DbSet<estadoHojaRuta> estadoHojaRuta { get; set; }
        public virtual DbSet<fechaTramo> fechaTramo { get; set; }
        public virtual DbSet<guias> guias { get; set; }
        public virtual DbSet<hojaRuta> hojaRuta { get; set; }
        public virtual DbSet<hojaRutaDetalle> hojaRutaDetalle { get; set; }
        public virtual DbSet<hojaRutaDetalleGuia> hojaRutaDetalleGuia { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
    }
}
